### ISSUE TITLE
strange translation in zh-tw page

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/experience-manager-65.zh-Hant#1]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

the translation is weird, click what? something is missing in brackets

按一下「 」，上傳憑證檔案 選擇證書鏈檔案.

**Comment by adobechienan** [comment]
@yanlicao Thank you. We are looking into this issue.

**Comment by adobechienan** [comment]
@yanlicao Thank you for your feedback. This is being reviewed and tracked in G11N-10824.

**Comment by adobechienan** [comment]
@yanlicao Please note that this issue should now be resolved.
